name: 06 - Variables y secretos
on:
  push:
    branches: [ "main" ]
  workflow_dispatch:

env:
  COLOR_PILDORA: "${{ vars.COLOR_PILDORA || 'Azul' }}"

jobs:
  the-matrix:
    runs-on: ubuntu-latest
    steps:
      - name: Elección de Neo
        run: echo "Neo, has decidido tomar la píldora ${{ env.COLOR_PILDORA }}"

      - name: Saber la verdad
        if: "${{ env.COLOR_PILDORA == 'Roja' }}"
        run: |
          echo "Neo, la realidad no es lo que piensas"
          echo "Te diré un secreto: ${{ secrets.TODO_ES_MENTIRA }}"
          echo "${{ secrets.TODO_ES_MENTIRA }}" | sed 's/./& /g'

      - name: Seguir con tu vida
        if: "${{ env.COLOR_PILDORA == 'Azul' }}"
        run: |
          echo "Neo, sigue con tu vida"
